name: caller-workflow-singlejob

on:
  workflow_dispatch

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: BunnyOrg/Org-marketplace/.github/actions/checkout@main

      - name: Print txt file
        shell: bash
        run: |
         echo "**********************"
         cat sample.txt
         echo "**********************"
