name: caller-workflow-singlejob

on:
  workflow_dispatch

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print txt file
        shell: bash
        run: |
         echo "**********************"
         cat sample.txt
         echo "**********************"

      - name: compile C code
        uses: BunnyOrg/Org-marketplace/actions/compile@main
        with:
          c_file: "/sample.c"
